52 shop info
fun-dev/hakodate-sweets-management-web pull request #76
Opened 2020-08-28 06:00 UTC by YukiTodate

## 概要

closes #IssueNo#52

- 店舗情報の表示画面を実装

## 確認方法

1. `/shops` を開く
1. 適当な店舗を選択して`/shops/[shopId]`を開く

## 確認事項
1. 下記の画像のように表示されているか
1. UI, UXな側面で問題ないか
1. 戻るボタンの挙動
1. 必要な全ての情報が記載されているか

<img width="1422" alt="スクリーンショット 2020-08-28 14 53 35" src="https://user-images.githubusercontent.com/28826067/91526422-8a8d9480-e93e-11ea-821c-1d67f216591a.png">

## その他
- 店舗の画像を大きくしたいが，そうするとリストをはみ出して表示されてしまうため未実装

2020-08-28 06:02 UTC, YukiTodate commented
@YTakahashii よろしく〜

2020-08-29 10:36 UTC, YTakahashii commented on src/components/partials/ShopDetail/ShopInformationColumn/ShopInformationColumn.tsx
> +          <Divider variant="middle" />
ここの部分が繰り返されているので， `<ShopInformationColumn />` としてコンポーネントに分けよう

2020-08-29 10:36 UTC, YTakahashii commented on src/components/partials/ShopDetail/ShopInformationColumn/ShopInformationColumn.tsx
> +type keys = keyof Shop;
使ってないので消す

2020-08-29 10:37 UTC, YTakahashii commented on src/components/partials/ShopDetail/ShopInformationColumn/ShopInformationColumn.tsx
> +import {
`ShopInformation/ShopInformationColumn.tsx` にディレクトリの構造を変えよう

2020-08-29 10:38 UTC, YTakahashii requested changes
修正お願いします！

2020-09-30 02:18 UTC, YukiTodate commented
@YTakahashii 修正しました！

2020-09-30 02:26 UTC, YukiTodate commented
> 店舗の画像を大きくしたいが，そうするとリストをはみ出して表示されてしまうため未実装
この問題は解決できてない><

2020-09-30 03:01 UTC, YTakahashii commented on src/components/partials/ShopDetail/index.tsx
> +import React from 'react';
この `ShopDetail/ShopInformationColumn/index.ts` なんだけど， このファイルとフォルダは削除して
`ShopDetail/ShopInformation/ShopInformationColumn/index.ts` を作成してその中身を以下のようにしないとエラーでてしまうね．

```.ts
export * from './ShopInformationColumn'
```

<img width="981" alt="localhost_3000_shops_1" src="https://user-images.githubusercontent.com/18653847/94638312-a48f0e00-0314-11eb-9de4-bf3d0778b47f.png">

2020-09-30 03:02 UTC, YTakahashii commented on src/components/partials/ShopDetail/ShopInformation/ShopInformationColumn/ShopInformationColumn.tsx
> +    },
使ってないから消して良さそう

2020-09-30 03:02 UTC, YTakahashii commented on src/components/partials/ShopDetail/ShopInformation/ShopInformationColumn/ShopInformationColumn.tsx
> +} from '@material-ui/core';
使っていないimportがいくつか入っているから，確認して消してね

2020-09-30 03:03 UTC, YTakahashii commented on src/components/partials/ShopDetail/ShopInformation/ShopInformationColumn/ShopInformationColumn.tsx
> +import { useShop } from 'src/lib/api/requests/useShop';
これも使ってない

2020-09-30 03:03 UTC, YTakahashii commented on src/components/partials/ShopDetail/ShopInformation/ShopInformationColumn/ShopInformationColumn.tsx
> +type keys = keyof Shop;
`keys` も消そう

2020-09-30 03:04 UTC, YTakahashii commented on src/components/partials/ShopDetail/ShopInformation/ShopInformationColumn/ShopInformationColumn.tsx
> +  //const { data } = useShop({ id: shopId });
このコメント部分も消そう

2020-09-30 03:05 UTC, YTakahashii requested changes
@YukiTodate 
確認お願いします！

2020-09-30 03:09 UTC, YTakahashii commented
@YukiTodate 
画像の大きさは下みたいなやり方でstyledを使うとCSSを当てられる気がするからちょっとやってみてほしい！

```.tsx
import { ListItemAvatar as MaterialListItemAvatar } from '@material-ui/core';
import styled from 'styled-components';

const ListItemAvatar = styled(MaterialListItemAvatar)`
	// この中に普通のCSSを書く
	color: red;
`;
```

2020-09-30 05:15 UTC, YukiTodate commented
@YTakahashii 画像のサイズのところ以外直した〜

2020-10-05 07:04 UTC, YTakahashii approved these changes
🙆‍♂️

2020-10-05 07:04 UTC, merged